spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: /upload/
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_management_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Australia/Sydney
    username: root
    password: 123456
  redis:
    port: 6379
    host: 192.168.56.10
server:
  port: 9999
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    edu.dhs.bookmanagementsystem: debug