spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: /upload/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_management_system?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Australia/Sydney
    username: root
    password: 123456
  cloud:
    alicloud:
      access-key: LTAI5tB9abvQYv5UDLSDEmWC
      secret-key: 2kGvB8RD9oEjgOkQrbOEkAlejWHPrr
      oss:
        endpoint: oss-ap-southeast-2.aliyuncs.com
        bucket: dhs-book-management
#  redis:
#    port: 6379
#    host: localhost
server:
  port: 9999
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: edu.dhs.bookmanagementsystem.entity
logging:
  level:
    edu.dhs.bookmanagementsystem: debug

book-management:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10